### ISSUE TITLE
ballball大佬康康，第二次workflow运行结束后失败了，看不懂这个错误Process completed with exit code 255.谢谢啦！

### ISSUE THREAD

**Issue by ghost** [shuzang/shuzang.github.io#1]
我是跟着你的教程做的，第一次推送workflow运行结束成功，第二次添加主题后出现了错误。我也没有改动过主题文件夹/layouts/partials/init.htm

**以下是网页端运行日志，不知道怎么修改**
> Run hugo --minify
WARN 2020/07/07 15:27:20 Module "LoveIt" is not compatible with this Hugo version; run "hugo mod graph" for more information.
Error: add site dependencies: load resources: loading templates: "/home/runner/work/aynix.github.io/aynix.github.io/themes/LoveIt/layouts/partials/init.html:35:1": parse failed: template: partials/init.html:35: function "warnf" not defined
##[error]Process completed with exit code 255.

**这是邮箱收到的错误信息：**
Run failed for blog (70ebc90)

Repository: aynix/aynix.github.io
Workflow: hugo push to github pages
Duration: 29.0 seconds
Finished: 2020-07-07 15:27:24 UTC
View results
Jobs:
build-deploy failed (1 annotation)

**这是遇到问题的界面截图：**
https://i.loli.net/2020/07/07/AR6eKHmzCkcIoG8.png

hugo：v0.73.0/extended windows/amd64
博客托管在 Github Pages 上，主题是最新的，谢谢大佬呀

**Comment by shuzang** [comment]
应该是 Hugo 版本太高了吧，Hugo 的版本迭代比较快，有时候主题开发者的支持速度跟不上。我还以为 Hugo 版本还在 0.6，结果就 0.7 了，我看了一下，0.7 版本的更新在5月份，LoveIt 主题的作者应该是没适配，你试着将版本降到 0.7 以下试试，如果不行就慢慢一直往下降低版本。




------------------&nbsp;原始邮件&nbsp;------------------


 
我是跟着你的教程做的，第一次推送workflow运行结束成功，第二次添加主题后出现了错误。
 以下是网页端运行日志，我实在不知道怎么修改。我也没有改动过主题文件夹/layouts/partials/init.html
 ##[error]Process completed with exit code 255.
 Run hugo --minify
 WARN 2020/07/07 15:27:20 Module "LoveIt" is not compatible with this Hugo version; run "hugo mod graph" for more information.
 Error: add site dependencies: load resources: loading templates: "/home/runner/work/aynix.github.io/aynix.github.io/themes/LoveIt/layouts/partials/init.html:35:1": parse failed: template: partials/init.html:35: function "warnf" not defined
 ##[error]Process completed with exit code 255.
 
这是遇到问题的界面截图
 https://i.loli.net/2020/07/07/AR6eKHmzCkcIoG8.png
 
hugo：v0.73.0/extended windows/amd64
 博客托管在 Github Pages 上，主题是最新的，谢谢大佬呀
 
—

**Comment by ghost** [comment]
> 应该是Hugo版本太高了吧，Hugo版本更新比较快，有时候主题开发者的支持速度跟不上。我还以为Hugo版本还在0.6，结果就0.7了，我看了一下，0.7版本的更新在5月，LoveIt主题的作者应该是没适应，你试着将版本降到0.7以下试试，如果不行就慢慢一直往往降低版本。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 我是跟着你的教程做的，第一次推送workflow运行结束成功，第二次添加主题后出现了错误。 以下是网页端运行日志，我实在不知道怎么修改。我也没有改动过主题文件夹/layouts/partials/init.html ##[error]Process completed with exit code 255. Run hugo --minify WARN 2020/07/07 15:27:20 Module "LoveIt" is not compatible with this Hugo version; run "hugo mod graph" for more information. Error: add site dependencies: load resources: loading templates: "/home/runner/work/aynix.github.io/aynix.github.io/themes/LoveIt/layouts/partials/init.html:35:1": parse failed: template: partials/init.html:35: function "warnf" not defined ##[error]Process completed with exit code 255. 这是遇到问题的界面截图 https://i.loli.net/2020/07/07/AR6eKHmzCkcIoG8.png hugo：v0.73.0/extended windows/amd64 博客托管在 Github Pages 上，主题是最新的，谢谢大佬呀 —

好的，谢谢！我去试试！！我打算重新来一遍来着。
